/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

/**
 *
 * @author Lasitha
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuStudent = new javax.swing.JMenuItem();
        mnuLecturer = new javax.swing.JMenuItem();
        mnuModule = new javax.swing.JMenuItem();
        mnuClose = new javax.swing.JMenuItem();
        mnuRegister = new javax.swing.JMenu();
        mnuRegisterStudentToModules = new javax.swing.JMenuItem();
        mnuRegisterLecturersToModules = new javax.swing.JMenuItem();
        mnuLogin = new javax.swing.JMenu();
        mnuNewUser = new javax.swing.JMenuItem();
        mnuChangePassword = new javax.swing.JMenuItem();
        mnuDeleteUser = new javax.swing.JMenuItem();
        mnuLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("XYZ Institute");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Student Management System");

        mnuFile.setText("File");

        mnuStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuStudent.setText("Student");
        mnuStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStudentActionPerformed(evt);
            }
        });
        mnuFile.add(mnuStudent);

        mnuLecturer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuLecturer.setText("Lecturer");
        mnuLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLecturerActionPerformed(evt);
            }
        });
        mnuFile.add(mnuLecturer);

        mnuModule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuModule.setText("Module");
        mnuModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModuleActionPerformed(evt);
            }
        });
        mnuFile.add(mnuModule);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuClose);

        jMenuBar1.add(mnuFile);

        mnuRegister.setText("Register");

        mnuRegisterStudentToModules.setText("Register Student to Modules");
        mnuRegisterStudentToModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegisterStudentToModulesActionPerformed(evt);
            }
        });
        mnuRegister.add(mnuRegisterStudentToModules);

        mnuRegisterLecturersToModules.setText("Register Lecturers to Modules");
        mnuRegisterLecturersToModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegisterLecturersToModulesActionPerformed(evt);
            }
        });
        mnuRegister.add(mnuRegisterLecturersToModules);

        jMenuBar1.add(mnuRegister);

        mnuLogin.setText("Login");

        mnuNewUser.setText("New User");
        mnuNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewUserActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuNewUser);

        mnuChangePassword.setText("Change Password");
        mnuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePasswordActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuChangePassword);

        mnuDeleteUser.setText("Delete User");
        mnuDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteUserActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuDeleteUser);

        mnuLogOut.setText("Log Out");
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuLogOut);

        jMenuBar1.add(mnuLogin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStudentActionPerformed
        // TODO add your handling code here:
        StudentUI sui=new StudentUI();
        sui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuStudentActionPerformed

    private void mnuLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLecturerActionPerformed
        // TODO add your handling code here:
        LecturerUI lui=new LecturerUI();
        lui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuLecturerActionPerformed

    private void mnuModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModuleActionPerformed
        // TODO add your handling code here:
        ModuleUI mui=new ModuleUI();
        mui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuModuleActionPerformed

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuRegisterStudentToModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegisterStudentToModulesActionPerformed
        // TODO add your handling code here:
        RegistrationUI rui=new RegistrationUI();
        rui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuRegisterStudentToModulesActionPerformed

    private void mnuRegisterLecturersToModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegisterLecturersToModulesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuRegisterLecturersToModulesActionPerformed

    private void mnuNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewUserActionPerformed
        // TODO add your handling code here:
        NewUserUI nuui=new NewUserUI();
        nuui.setVisible(true);
    }//GEN-LAST:event_mnuNewUserActionPerformed

    private void mnuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePasswordActionPerformed
        // TODO add your handling code here:
        ChangePasswordUI cpui=new ChangePasswordUI();
        cpui.setVisible(true);
    }//GEN-LAST:event_mnuChangePasswordActionPerformed

    private void mnuDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteUserActionPerformed
        // TODO add your handling code here:
        DeleteUserUI duui=new DeleteUserUI();
        duui.setVisible(true);
    }//GEN-LAST:event_mnuDeleteUserActionPerformed

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
        // TODO add your handling code here:
        LoginUI lui=new LoginUI();
        lui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuChangePassword;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuDeleteUser;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuLecturer;
    private javax.swing.JMenuItem mnuLogOut;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenuItem mnuModule;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenu mnuRegister;
    private javax.swing.JMenuItem mnuRegisterLecturersToModules;
    private javax.swing.JMenuItem mnuRegisterStudentToModules;
    private javax.swing.JMenuItem mnuStudent;
    // End of variables declaration//GEN-END:variables
}
